1. Crie um vetor numpy com os números pares de 1 a 20. Dica: use np.arange()

In [1]:
import numpy as np

pares = np.arange(0, 20, 2, dtype=int)

pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

2. Crie uma matriz numpy 3x3 com valores aleatórios entre 0 e 10. Dica: use np.random.rand()

In [ ]:
matrizAleatoria = np.random.uniform(low=0, high=10, size=(3,3))
matrizAleatoria

## forma com int
matrizAleatoriaInt = np.random.randint(low=0, high=10, size=(3,3))
matrizAleatoriaInt


[[5.22184745 9.56267449 3.57299324]
 [5.35102335 3.47796387 3.27739209]
 [8.17606871 1.24168649 7.33667963]]
[[1 2 0]
 [6 0 3]
 [1 4 7]]


3. Multiplique todos os elementos de um vetor por 2. Use broadcasting para evitar loop.

Exemplo: Seja 'vetor = np.array([1, 2, 3, 4])'.

O resultado esperado: 'array ([2, 4, 6, 8])'.

In [ ]:
vetor = np.array([1, 2, 3, 4])
vetorX2 = vetor * 2

vetorX2

[2 4 6 8]


4. Calcule a soma cumulativa de um vetor. Dica: usar np.cumsum()

Exemplo: Seja 'vetor = np.array([1, 2, 3, 4])', o resultado seria 'array([ 1, 3, 6, 10])'.

In [ ]:
vetor4 = np.array([1, 2, 3, 4])
vetor4C = np.cumsum(vetor4)

vetor4C

[ 1  3  6 10]


5. Transponha uma matriz.

Exemplo: Seja `matriz = np.array([[1, 2], [3, 4], [5, 6]])`, o resultado seria `array([[1, 3,
5], [2, 4, 6]])`

In [ ]:
matriz = np.array([[1, 2], [3, 4], [5, 6]])
matrizT = np.transpose(matriz)

matrizT

[[1 3 5]
 [2 4 6]]


6. Converta uma matriz em um vetor unidimensional.

Exemplo: Seja `matriz = np.array([[1, 2, 3], [4, 5, 6]])`, o resultado seria `array([1, 2, 3,
4, 5, 6])`

In [ ]:
matriz6 = np.array([[1, 2, 3], [4, 5, 6]])
matriz6Uni = np.reshape(matriz6, 6)
matriz6Uni

[1 2 3 4 5 6]


7. Multiplicação matricial: multiplique uma matriz (m × n) por um vetor (n × 1).

Exemplo: Seja `matriz = np.array([[1, 2], [3, 4]])` e `vetor = np.array([[5], [6]])`, o
resultado seria `array([[17], [39]])`

In [ ]:
matriz7 = np.array([[1, 2], [3, 4]])
vetor7 = np.array([[5], [6]])

resultado7 = matriz7 @ vetor7

resultado7

[[17]
 [39]]


8. Encontre os índices dos valores máximos em cada linha de uma matriz. Dica: use
np.argmax().

Exemplo: Seja `matriz = np.array([[1, 9, 6], [8, 2, 3], [4, 7, 5]])`, o resultado
seria `array([1, 0, 1])`

In [ ]:
matriz8 = np.array([[1, 9, 6], [8, 2, 3], [4, 7, 5]])
#axis = 0 // coluna || axis = 1 // linha
matriz8MaxIndice = np.argmax(matriz8, axis=1)

matriz8MaxIndice

[1 0 1]


9. Calcule a raiz quadrada de todos os elementos de um vetor.


Exemplo: Seja `vetor = np.array([4, 9, 16, 25])`, o resultado seria `array([2., 3., 4., 5.])`

In [ ]:
vetor9 = np.array([4, 9, 16, 25])
vetor9Raiz = np.sqrt(vetor9)

vetor9Raiz

[2. 3. 4. 5.]


10. Substitua todos os valores negativos em um vetor por 0.

Exemplo: Seja `vetor =
np.array([-1, 2, -3, 4, -5])`, o resultado seria `array([0, 2, 0, 4, 0])`

In [ ]:
vetor10 = np.array([-1, 2, -3, 4, -5])
result10 = np.maximum(vetor10, 0)

result10

array([0, 2, 0, 4, 0])

11. Reshape um vetor unidimensional em uma matriz 3x3.

Exemplo: Seja `vetor =
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])`, o resultado seria `array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`

In [ ]:
vetor11 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
vetor113x3 = np.reshape(vetor11, (3, 3))

vetor113x3

[[1 2 3]
 [4 5 6]
 [7 8 9]]


12. Adicione um valor constante a todos os elementos de um vetor.


Exemplo: Seja `vetor = np.array([1, 2, 3, 4])` e `constante = 5`, o resultado seria
`array([6, 7, 8, 9])`

In [ ]:
vetor12 = np.array([1, 2, 3, 4])
constante = 5
vetor12Constante = vetor12 + constante

vetor12Constante

[6 7 8 9]


13. Determine uma constante que ao multiplicar todos os elementos de uma matriz por
essa constante, a soma dos elementos da matriz resultante será 1. Não usar loops.

Exemplo: Seja `matriz = np.array([[1, 2], [3, 4]])`, o resultado seria `array([[0.1, 0.2], [0.3, 0.4]])`, pois 0.1+0.2+0.3+0.4 = 1.

In [ ]:
matriz13 = np.array([[1, 2], [3, 4]])
soma = np.sum(matriz13)
matriz13Constante = matriz13 * ( 1 / soma)

matriz13Constante

array([[0.1, 0.2],
       [0.3, 0.4]])

14. Gere uma matriz identidade 3x3. Dica: use np.eye()

In [ ]:
matriz14 = np.eye(3,3)
matriz14

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

15. Concatene duas matrizes horizontalmente. Dica: use np.hstack()
Exemplo:

In [ ]:
matriz1 = [[1, 2, 3],
           [4, 5, 6]]
matriz2 = [[7, 8, 9],
           [10, 11, 12]]
matriz3 = np.hstack((matriz1, matriz2))

matriz3

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

16. Encontre o produto escalar entre os vetores [1, 2, 3] e [4, 5, 6]. Dica: use np.dot() e
também o operador @ para conferir o outro resultado

In [ ]:
vetor1 = [1, 2, 3]
vetor2 = [4, 5, 6]

resultado1 = np.dot(vetor1, vetor2)
resultado1

32

17. Calcule a média e o desvio padrão de cada linha de uma matriz. Dica: use np.mean() e
np.std().

Exemplo: `matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`. O resultado deve ser:
média por linha: [2. 5. 8.], desvio padrão por linha: [0.8165, 0.8165, 0.8165]

In [ ]:
matriz17 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
media17 = np.mean(matriz17, axis=1)
desvio17 = np.std(matriz17, axis=1)
print(matriz17)
print(f"média por linha: {media17}")
print(f"desvio padrão por linha: {desvio17}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
média por linha: [2. 5. 8.]
desvio padrão por linha: [0.81649658 0.81649658 0.81649658]


18. Calcule a média e o desvio padrão de cada coluna de uma matriz. Dica: use np.mean()
e np.std().

Exemplo: matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]). O resultado deve ser:
média por coluna: [4. 5. 6.], desvio padrão por coluna: [2.4495, 2.4495, 2.4495]

In [ ]:
matriz18 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
media18 = np.mean(matriz18, axis=0)
desvio18 = np.std(matriz18, axis=0)
print(matriz18)
print(f"média por coluna: {media18}")
print(f"desvio padrão por coluna: {desvio18}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
média por coluna: [4. 5. 6.]
desvio padrão por coluna: [2.44948974 2.44948974 2.44948974]


19. Calcule a média de cada coluna de uma matriz e a subtraia da respectiva coluna.

Exemplo: Seja `matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`, o resultado seria
`array([[-3., -3., -3.], [ 0., 0., 0.], [ 3., 3., 3.]])`. Use broadcasting para evitar loops

In [ ]:
matriz19 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
media19 = np.mean(matriz19, axis=0)
broadcast19 = matriz19 - media19

print(matriz19)
print(f"\nmédia por coluna: {media19}")
print(f"\no resultado:\n {broadcast19}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]

média por coluna: [4. 5. 6.]

o resultado:
 [[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]


20. Calcule a média de cada linha de uma matriz e a subtraia da respectiva linha.

Exemplo:
Seja `matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`, o resultado seria `array([[-1., 0., 1.],
[-1., 0., 1.], [-1., 0., 1.]])`. Use broadcasting para evitar loops

In [ ]:
matriz20 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
media20 = np.mean(matriz20, axis=1)
matriz20T = np.transpose(matriz20)
broadcast20 = np.transpose(matriz20T - media20)

print(matriz20)
print(f"\nmédia por linha: {media20}")
print(f"\no resultado:\n {broadcast20}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]

média por linha: [2. 5. 8.]

o resultado:
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


21. Uma operação comum em ciência de dados ou aprendizado de máquina é a normalização dos dados. Os
dados estão dispostos em uma matriz e cada característica de interesse ao longo das colunas. Por exemplo,
uma matriz em que cada linha corresponde a uma pessoa, teremos a coluna das idades, a coluna das
alturas, a coluna da renda mensal, etc. A normalização consiste em, para cada ponto na matriz, subtrair a
média da coluna e dividir pelo desvio padrão da respectiva coluna.
Normalize os dados da seguinte matriz X, onde cada linha corresponde a uma amostra (e.g. pessoa) e cada
coluna corresponde a uma característica dela. Para normalizar os dados, você pode usar broadcasting para
subtrair a média de cada coluna e dividir pelo desvio padrão, evitando a necessidade de loops explícitos.
Dica: use os métodos mean(), std() para os cálculos da média e desvio padrão, respectivamente.

In [ ]:
matrizX = np.array([[ 55, 1.72, 603 ], [ 54, 1.42, 646 ], [ 44, 1.89, 964 ], [ 38, 1.79, 529 ]])
matrizXT = np.transpose(matrizX)
mediaX = np.mean(matrizXT, axis=1)
desvioX = np.std(matrizXT, axis=1)
resultado = (matrizX - mediaX)/desvioX
resultado

array([[ 1.02338778,  0.08557469, -0.49654442],
       [ 0.88223084, -1.62591903, -0.23773945],
       [-0.5293385 ,  1.05542112,  1.67621359],
       [-1.37628011,  0.48492322, -0.94192972]])

22. Encontre a solução para o seguinte problema. Arredondar todos os valores em uma
matriz para o inteiro mais próximo. Dica: analise np.floor(), np.ceil(), np.fix() e np.round()

In [ ]:
matriz22 = np.array([[ 1.2, 2.8, 3.5 ], [ 4.9, 5.1, 6.7 ], [ 7.3, 8.6, 9.2 ]])
matriz22Arredondada = np.round(matriz22)
matriz22Arredondada

array([[1., 3., 4.],
       [5., 5., 7.],
       [7., 9., 9.]])

23. Dada a matriz A, encontre sua inversa A^-1
. Então, conprove que A A^-1 = I, onde I é a matriz identidade, com elementos da diagonal unitários e o restante zero.

In [ ]:
matriz23A = np.array([[1, 3, 2], [5, 4, 6], [7, 8, 9]])
matriz23AInv = np.linalg.inv(matriz23A)

matriz23I = matriz23A @ matriz23AInv
matriz23I

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-8.88178420e-16,  1.00000000e+00, -1.77635684e-15],
       [ 4.44089210e-16,  3.55271368e-15,  1.00000000e+00]])

24. Suponha que você seja um corretor imobiliário e deseja prever o preço de uma casa com base em diferentes características, como área construída, número de quartos, número de banheiros e idade da casa. Você coletou dados de venda de casas nos últimos seis meses e registrou essas características para cada venda.
Os dados coletados estão disponíveis na forma de uma matriz, onde cada linha representa uma casa vendida e cada coluna representa uma característica. Além disso, você tem um vetor com os preços de venda correspondentes das casas.

Tarefa: Encontrar os coeficientes ideais que relacionam as características das casas com os preços de venda. Em seguida, preveja o preço de uma nova casa com as seguintes características:
- Área construída: 180 metros quadrados
- Número de quartos: 3
- Número de banheiros: 2
- Idade da casa: 10 anos

(Resposta: 355000)

In [ ]:
casas = np.array([[ 150, 3, 2, 5 ], [ 200, 4, 3, 7 ], [ 180, 3, 2, 10 ], [ 170, 3, 2, 10 ], [ 220, 4, 3, 8 ], [ 190, 3, 2, 6 ]])
casaNova = np.array([[ 180, 3, 2, 10 ]])
valores = np.array([ 300000, 400000, 350000, 250000, 420000, 380000])

X, residuals, _, _ = np.linalg.lstsq(casas, valores, rcond=None)

print("X:", np.round(X,2))

estimado = casas @ X
estimadoNova = casaNova @ X
diferenca = (estimado - valores) / valores
print("Estimado:", np.round(estimado, 2))
print("Estimado Casa Nova:", np.round(estimadoNova, 2))
print("Real:", valores)
print("(Estimado - Real)/Real:", diferenca)

X: [  2561.29  -7050.4   -2109.52 -12445.55]
Estimado: [296596.14 390609.83 311207.22 285594.28 429390.17 386602.36]
Estimado Casa Nova: [311207.22]
Real: [300000 400000 350000 250000 420000 380000]
(Estimado - Real)/Real: [-0.01134619 -0.02347542 -0.11083652  0.1423771   0.02235754  0.01737464]
